### ISSUE TITLE
Cards Selection 

### ISSUE THREAD

**Issue by cintferreira** [envisioning/ev109_deftech#16]

**Comment by michellzappa** [comment]
Selecionar 3 cartas por cluster para indicar na página.

**Comment by arthursoares** [comment]
*Cyborg Soldier*
Artificial Intelligent Limb
Retinal Hacking Device
Military Exoskeleton

*Automated Logistics*
Pocket Surveillance Drone
Battlefield Rescue Robot
Autonomous Four-Legged Cargo Robot

*Hacking Emotions*
AI-Powered Interrogation Software
Moral Database
Mental Disorder Automated Identification

*AI Counselor*
AI Military Strategist
Intelligent AR Goggles
Predictive Counter-Terrorist Application

*IoT Conflict*
AI-Powered Cyber-Offence
Autonomous Robot Hijacking
Automated Insider Threat Detection

*Robot War*
Robotic Training Ground
Swarm Robotics
Artificial Moral Agent
