### ISSUE TITLE
Presentation texts

### ISSUE THREAD

**Issue by thomazrezende** [envisioning/ev109_deftech#22]
# CREATE
- HELP INTRO (optional)
- READINESS DESCRIPTION
- IMPACT DESCRIPTION 
___
# REVIEW

- IDEA DESCRIPTION
Lowest level of technology readiness. Scientific research begins to be translated into applied research and development (R&D). Examples might include paper studies of a technology’s basic properties. 

- CONCEPT DESCRIPTION
Invention begins. Once basic principles are observed, practical applications can be invented. Applications are speculative, and there may be no proof or detailed analysis to support the assumptions. Basic technological components are integrated to establish that they will work together. This is relatively “low fidelity” compared with the eventual system. 

- PROTOTYPE DESCRIPTION
Representative model or prototype system is tested in a relevant environment. Represents a major step up in a technology’s demonstrated readiness. Examples include testing a prototypein a high-fidelity laboratory environment or in a simulated operational environment. 

- PRODUCT DESCRIPTION
Technology has been proven to work in its final form and under expected conditions. In almost all cases, this level represents the end of true system development. Examples include developmental test and evaluation (DT&E) of the system in its intended weapon system to determine if it meets design specifications.
___
**INFO PAGE:**
DEFTECH ​Technology Foresight is a research program from armasuisse Science and Technology which goal is to anticipate and get the necessary understanding of the emerging technologies which might have their implications for the military in general and the Swiss armed forces in particular.

Envisioning is a virtual research institute. We provide technological foresight to policy and decision makers worldwide. Our global team of academics, hackers and designers study technology to understand accelerating change. We share our work with our own tools, methodology and design. 

METHODOLOGY 
The relative level of technological evolution has been estimated using Envisioning’s open-source Readiness methodology.Find out more:
___
**HOME PAGE**
Artificial intelligence is no longer science fiction.

The personal assistants in our phones are just the tip of the iceberg. AI systems are getting more powerful everyday: they can already read, hear, talk, translate, understand feelings and, ultimately, learn by themselves. Besides, advances in robotics are enabling a powerful embodiment to these new minds, connecting them not only with other machines, but also boosting the human body.

From healthcare to infrastructure, AI and robotics are quietly entering every aspect of life. And national security isn't - and can't be - an exception.

In this study, we mapped and analysed dozens of emerging technologies that combine artificial intelligence & robotics with defense applications. In that, we found that they have an indisputable potential to change the battlefield - from ground, air and sea to the cyberspace - generating new paradigms and remodeling defense as we know it.

Our aim is to raise awareness about the future of defense, spark debates and generate insight.

**Comment by thiaracavadas** [comment]
**# REVIEW** 

READINESS

Readiness is our model for assessing the development of emerging technologies. 

Every technology begins as an idea. Some spring from academic insights, some generated in R&D projects, while others can be found in the pages of science fiction. Some of these ideas are further developed into concepts, beginning an experimental life of increased application. Some concepts become prototypes, tested at scale. Some prototypes eventually become products, bringing availability to the public.

Those evolutionary steps produce signs that can be analyzed, such as growing competition, investment stage and public desire. Using expert input, our model measures signs of development from five different angles, producing a quantifiable indicator of how far a technology is from mainstream.

**Comment by thiaracavadas** [comment]
IMPACT

An expert score on the potential of a technology to change an industry.

**Comment by thiaracavadas** [comment]
# REVIEW

METHODOLOGY

Technology is everything we create; It is how humans have been solving problems and changing its reality since the stone age. Studying emerging technologies is at the core of our future studies methodology, because it allows us to understand what is yet to come and get a glimpse of the future.

We’ve curated **XX** emerging technologies using our global network of specialists. Every selected technology has had their readiness & impact levels gauged*, allowing us to understand them further. After mapping, combining and essaying these technologies, we come up with 6 scenarios that will alter the defence landscape.

*linkar com help page
